# Настройки плагина UniversalEc
# Доступные языки в папке lang: ru, en
lang: "ru"

# Настройки звуков при открытии эндер-сундука.
# Список доступных звуков для версии 1.21+: https://jd.papermc.io/paper/1.21/org/bukkit/Sound.html
sound:
  enabled: true
  name: "BLOCK_ENDER_CHEST_OPEN" # Стандартный звук открытия эндер-сундука
  volume: 1.0 # Громкость (от 0.0 до 1.0)
  pitch: 1.0  # Тональность (от 0.5 до 2.0)

# Настройки скрытности: если у игрока нет прав, плагин будет просто молчать в чат.
# true - плагин молчит (игрок даже не узнает, что это заблокировано)
# false - отправляет сообщение об ошибке прав из файла локализации
silent-mode:
  on-command-ec: false       # Скрытность для команды /ec
  on-click-hand: true        # Скрытность для клика сундуком из руки
  on-command-admin: false    # Скрытность для админ-команды /unec