# UniversalEc plugin settings
# Available languages in the folder "lang": ru, en
lang: "ru"

# Sound settings for opening an ender chest.
# List of available sounds for version 1.21+: https://jd.papermc.io/paper/1.21/org/bukkit/Sound.html
sound:
  enabled: true
  name: "BLOCK_ENDER_CHEST_OPEN" # The default sound of an ender chest opening.
  volume: 1.0 # Volume (0.0 to 1.0)
  pitch: 1.0  # Pitch (0.5 to 2.0)

# Silent settings: If the player does not have rights, the plugin will simply remain silent in the chat.
# true - the plugin is silent (the player will not even know that it is blocked)
# false - sends a permission error message from the localization file
silent-mode:
  on-command-ec: false       # Silent for the /ec command
  on-click-hand: true        # Silent for clicking the chest from your hand
  on-command-admin: false    # Silent for the /unec admin command