name: UniversalEc
version: '1.1'
main: io.github.lkorss.universalEc.UniversalEc
api-version: '1.21'
author: lkorss
website: https://github.com/lkorss/UniversalEc
description: A useful plugin for mobile ender chests for your server!

commands:
  ec:
    description: Open an ender chest remotely.
    permission: universalec.command.ec
    aliases: [enderchest, echest]
  unec:
    description: Managing the UniversalEc plugin.
    permission: universalec.admin
    aliases: [universalec]

permissions:
  universalec.command.ec:
    description: Allows you to open an ender chest with the /ec command.
    default: op
  universalec.use.click:
    description: Allows you to open an ender chest by right-clicking.
    default: op
  universalec.admin:
    description: Access to reload the plugin (/unec reload)
    default: op